name: 1.Build MiniOS LXFce Trixie Noble (Parallel)
on:
  workflow_dispatch:

env:
  TZ: Etc/GMT-7

jobs:
  build-trixie:
    name: Build Trixie Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune -a -f
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-build-armbian-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMinios.Skyline.Build.2026.tar.xz
          tar -xf zMinios.Skyline.Build.2026.tar.xz

      - name: Build | Trixie
        working-directory: /builder/zMinios.Skyline.Build.2026
        run: |
          sudo sh trixie.xfce.build.sh

      - name: Upload | Trixie ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-Trixie-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMinios.Skyline.Build.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30

      - name: Upload | Trixie SB
        uses: actions/upload-artifact@v4
        with:
          name: MiniOS-Trixie-SB-${{ steps.date.outputs.DATE }}
          path: /builder/zMinios.Skyline.Build.2026/build/trixie-standard-amd64/image/minios/*.sb*
          if-no-files-found: error
          retention-days: 30

  build-noble:
    name: Build Noble Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune -a -f
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-build-armbian-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMinios.Skyline.Build.2026.tar.xz
          tar -xf zMinios.Skyline.Build.2026.tar.xz

      - name: Build | Noble
        working-directory: /builder/zMinios.Skyline.Build.2026
        run: |
          sudo sh noble.xfce.build.sh

      - name: Upload | Noble ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-Noble-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMinios.Skyline.Build.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30
      - name: Upload | Noble SB
        uses: actions/upload-artifact@v4
        with:
          name: MiniOS-Noble-SB-${{ steps.date.outputs.DATE }}
          path: /builder/zMinios.Skyline.Build.2026/build/noble-standard-amd64/image/minios/*.sb*
          if-no-files-found: error
          retention-days: 30
