name: 2.Build Armbian LXFice CLi Aml-S9xx Uefi-x86

on:
  workflow_dispatch:

env:
  TZ: Etc/GMT-7
  BUILDER_DIR: /builder

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 600

    strategy:
      fail-fast: false
      matrix:
        include:
          # ===== Aml-S9xx GROUP =====
          - name: Armbian.LXFice.Forky.Aml-S9xx
            runs_on: ubuntu-24.04-arm
            board: aml-s9xx-box
            desktop: yes
            env_xfce: xfce
            config_name: config_base

          - name: Armbian.CLi.Forky.Aml-S9xx
            runs_on: ubuntu-24.04-arm
            board: aml-s9xx-box
            desktop: no
            env_xfce: ""
            config_name: ""

          # ===== Uefi-x86 GROUP =====
          - name: Armbian.LXFice.Forky.Uefi-x86
            runs_on: ubuntu-24.04
            board: uefi-x86
            desktop: yes
            env_xfce: xfce
            config_name: config_base

          - name: Armbian.CLi.Forky.Uefi-x86
            runs_on: ubuntu-24.04
            board: uefi-x86
            desktop: no
            env_xfce: ""
            config_name: ""

    steps:
      # =========================================
      # 1. INITIALIZE SYSTEM
      # =========================================
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Init & Dependencies
        run: |
          sudo timedatectl set-timezone "${TZ}"
          sudo swapoff -a || true
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl dosfstools mtools parted \
            e2fsprogs fdisk rsync lsof pv xfsprogs lvm2

      # =========================================
      # 2. CREATE LVM DISK
      # =========================================
      - name: Prepare | Create Virtual Disk
        run: |
          set -e
          sudo truncate -s 100G /mnt.img
          sudo truncate -s 100G /root.img

          LOOP1=$(sudo losetup --find --show /mnt.img)
          LOOP2=$(sudo losetup --find --show /root.img)

          sudo pvcreate $LOOP1 $LOOP2
          sudo vgcreate github $LOOP1 $LOOP2
          sudo lvcreate -n runner -l 100%FREE github

          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p $BUILDER_DIR
          sudo mount /dev/github/runner $BUILDER_DIR
          sudo chown -R runner:runner $BUILDER_DIR
          df -Th

      # =========================================
      # 3. DOWNLOAD ARMBIAN BUILD SYSTEM
      # =========================================
      - name: Prepare | Clone Armbian
        working-directory: ${{ env.BUILDER_DIR }}
        run: |
          git clone --depth 1 https://github.com/1compk/armbian.build.git armbian

      # =========================================
      # 4. BUILD ARMBIAN
      # =========================================
      - name: Build | Armbian
        working-directory: ${{ env.BUILDER_DIR }}/armbian
        run: |
          chmod +x compile.sh
          sudo ./compile.sh build \
            EXPERT=yes \
            BOARD=${{ matrix.board }} \
            BRANCH=edge \
            RELEASE=forky \
            BUILD_DESKTOP=${{ matrix.desktop }} \
            BUILD_MINIMAL=no \
            DESKTOP_APPGROUPS_SELECTED= \
            DESKTOP_ENVIRONMENT=${{ matrix.env_xfce }} \
            DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ matrix.config_name }} \
            KERNEL_BTF=no \
            KERNEL_CONFIGURE=no \
            KERNEL_GIT=shallow \
            DOCKER_ARMBIAN=no \
            USE_CCACHE=no \
            COMPRESS_OUTPUTIMAGE=gz

      # =========================================
      # 5. UPLOAD ARTIFACTS
      # =========================================
      - name: Upload | Armbian Image
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}-${{ steps.date.outputs.DATE }}
          path: ${{ env.BUILDER_DIR }}/armbian/output/images/*.img*
          retention-days: 90
          archive: false
          if-no-files-found: error